spring:
  application:
    name: dossiermedical-service
  data:
    mongodb:
      uri: mongodb+srv://PediaLink:PediaLink@pedialink.0d8a5qd.mongodb.net/pedialink?retryWrites=true&w=majority
      auto-index-creation: true
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    tn.pedialink.dossiermedical: DEBUG
    org.springframework.data.mongodb: INFO
    org.mongodb.driver: INFO

server:
  port: 8084

# Force MongoDB Atlas connection
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
